import {
  flexRow,
  flexRowTab,
  flexRowMd,
  flexRowSm,
  flexRowXs,
} from "./flex/flexRow.style";
import {
  flexColumn,
  flexColumnTab,
  flexColumnMd,
  flexColumnSm,
  flexColumnXs,
} from "./flex/flexColumn.style";
import {
  flexOrder,
  flexOrderTab,
  flexOrderMd,
  flexOrderSm,
  flexOrderXs,
  flexGrow,
  flexGrowTab,
  flexGrowMd,
  flexGrowSm,
  flexGrowXs,
  flexShrink,
  flexShrinkTab,
  flexShrinkMd,
  flexShrinkSm,
  flexShrinkXs,
} from "./flex/flexItem.style";
import { fontSize } from "./fonts/font.style";
import {
  absolute,
  absoluteTab,
  absoluteMd,
  absoluteSm,
  absoluteXs,
  relative,
  relativeTab,
  relativeMd,
  relativeSm,
  relativeXs,
  staticPos,
  staticPosTab,
  staticPosMd,
  staticPosSm,
  staticPosXs,
  sticky,
  stickyTab,
  stickyMd,
  stickySm,
  stickyXs,
  fixed,
  fixedTab,
  fixedMd,
  fixedSm,
  fixedXs,
  top,
  topTab,
  topMd,
  topSm,
  topXs,
  left,
  leftTab,
  leftMd,
  leftSm,
  leftXs,
  right,
  rightTab,
  rightMd,
  rightSm,
  rightXs,
  bottom,
  bottomTab,
  bottomMd,
  bottomSm,
  bottomXs,
} from "./position/position.style";
import { backgroundColor, color } from "./background/background.style";
import {
  width,
  widthMd,
  widthSm,
  widthTab,
  widthXs,
} from "./mensuration/width/width.style";
import {
  height,
  heightTab,
  heightMd,
  heightSm,
  heightXs,
} from "./mensuration/height/height.style";
import {
  margin,
  marginTab,
  marginMd,
  marginSm,
  marginXs,
  marginBottom,
  marginBottomTab,
  marginBottomMd,
  marginBottomSm,
  marginBottomXs,
  marginLeft,
  marginLeftTab,
  marginLeftMd,
  marginLeftSm,
  marginLeftXs,
  marginRight,
  marginRightTab,
  marginRightMd,
  marginRightSm,
  marginRightXs,
  marginTop,
  marginTopTab,
  marginTopMd,
  marginTopSm,
  marginTopXs,
  marginX,
  marginXTab,
  marginXMd,
  marginXSm,
  marginXXs,
  marginY,
  marginYTab,
  marginYMd,
  marginYSm,
  marginYXs,
} from "./spacing/margin";

import {
  padding,
  paddingTab,
  paddingMd,
  paddingSm,
  paddingXs,
  paddingBottom,
  paddingBottomTab,
  paddingBottomMd,
  paddingBottomSm,
  paddingBottomXs,
  paddingLeft,
  paddingLeftTab,
  paddingLeftMd,
  paddingLeftSm,
  paddingLeftXs,
  paddingRight,
  paddingRightTab,
  paddingRightMd,
  paddingRightSm,
  paddingRightXs,
  paddingTop,
  paddingTopTab,
  paddingTopMd,
  paddingTopSm,
  paddingTopXs,
  paddingX,
  paddingXTab,
  paddingXMd,
  paddingXSm,
  paddingXXs,
  paddingY,
  paddingYTab,
  paddingYMd,
  paddingYSm,
  paddingYXs,
} from "./spacing/padding";

export const general = (props) => {
  let style = `
  ${flexRow(props)}
  ${flexColumn(props)}
  ${flexOrder(props)}
  ${flexGrow(props)}
  ${flexShrink(props)}
  ${fontSize(props)}
  ${absolute(props)}
  ${relative(props)}
  ${staticPos(props)}
  ${sticky(props)}
  ${fixed(props)}
  ${top(props)}
  ${left(props)}
  ${right(props)}
  ${bottom(props)}
  ${backgroundColor(props)}
  ${color(props)}
  ${width(props)}
  ${height(props)}
  ${margin(props)}
  ${marginX(props)}
  ${marginY(props)}
  ${marginTop(props)}
  ${marginLeft(props)}
  ${marginBottom(props)}
  ${marginRight(props)}
  ${padding(props)}
  ${paddingX(props)}
  ${paddingY(props)}
  ${paddingTop(props)}
  ${paddingLeft(props)}
  ${paddingBottom(props)}
  ${paddingRight(props)}

  @media screen and (max-width: ${props.theme.screen.tab}) {
  ${flexRowTab(props)}
  ${flexColumnTab(props)}
  ${flexOrderTab(props)}
  ${flexGrowTab(props)}
  ${flexShrinkTab(props)}
  ${absoluteTab(props)}
  ${relativeTab(props)}
  ${staticPosTab(props)}
  ${stickyTab(props)}
  ${fixedTab(props)}
  ${topTab(props)}
  ${leftTab(props)}
  ${rightTab(props)}
  ${bottomTab(props)}
  ${widthTab(props)}
    ${heightTab(props)}
    ${marginXTab(props)}
    ${marginYTab(props)}
    ${marginTab(props)}
  ${marginTopTab(props)}
  ${marginLeftTab(props)}
  ${marginBottomTab(props)}
  ${marginRightTab(props)}
  ${paddingXTab(props)}
  ${paddingYTab(props)}
  ${paddingTab(props)}
${paddingTopTab(props)}
${paddingLeftTab(props)}
${paddingBottomTab(props)}
${paddingRightTab(props)}
  }

  @media screen and (max-width: ${props.theme.screen.md}) {
  ${flexRowMd(props)}
  ${flexColumnMd(props)}
  ${flexOrderMd(props)}
  ${flexGrowMd(props)}
  ${flexShrinkMd(props)}
  ${absoluteMd(props)}
  ${relativeMd(props)}
  ${staticPosMd(props)}
  ${stickyMd(props)}
  ${fixedMd(props)}
  ${topMd(props)}
  ${leftMd(props)}
  ${rightMd(props)}
  ${bottomMd(props)}
  ${widthMd(props)}
    ${heightMd(props)}
    ${marginMd(props)}
    ${marginXMd(props)}
    ${marginYMd(props)}
  ${marginTopMd(props)}
  ${marginLeftMd(props)}
  ${marginBottomMd(props)}
  ${marginRightMd(props)}
  ${paddingMd(props)}
    ${paddingXMd(props)}
    ${paddingYMd(props)}
  ${paddingTopMd(props)}
  ${paddingLeftMd(props)}
  ${paddingBottomMd(props)}
  ${paddingRightMd(props)}
  }

  @media screen and (max-width: ${props.theme.screen.sm}) {
  ${flexRowSm(props)}
  ${flexColumnSm(props)}
  ${flexOrderSm(props)}
  ${flexGrowSm(props)}
  ${flexShrinkSm(props)}
  ${absoluteSm(props)}
  ${relativeSm(props)}
  ${staticPosSm(props)}
  ${stickySm(props)}
  ${fixedSm(props)}
  ${topSm(props)}
  ${leftSm(props)}
  ${rightSm(props)}
  ${bottomSm(props)}
  ${widthSm(props)}
    ${heightSm(props)}
    ${marginSm(props)}
    ${marginXSm(props)}
    ${marginYSm(props)}
  ${marginTopSm(props)}
  ${marginLeftSm(props)}
  ${marginBottomSm(props)}
  ${marginRightSm(props)}
  ${paddingSm(props)}
  ${paddingXSm(props)}
  ${paddingYSm(props)}
${paddingTopSm(props)}
${paddingLeftSm(props)}
${paddingBottomSm(props)}
${paddingRightSm(props)}
  }

  @media screen and (max-width: ${props.theme.screen.xs}) {
  ${flexRowXs(props)}
  ${flexColumnXs(props)}
  ${flexOrderXs(props)}
  ${flexGrowXs(props)}
  ${flexShrinkXs(props)}
  ${absoluteXs(props)}
  ${relativeXs(props)}
  ${staticPosXs(props)}
  ${stickyXs(props)}
  ${fixedXs(props)}
  ${topXs(props)}
  ${leftXs(props)}
  ${rightXs(props)}
  ${bottomXs(props)}
  ${widthXs(props)}
    ${heightXs(props)}
    ${marginXs(props)}
    ${marginXXs(props)}
    ${marginYXs(props)}
  ${marginTopXs(props)}
  ${marginLeftXs(props)}
  ${marginBottomXs(props)}
  ${marginRightXs(props)}
  ${paddingXs(props)}
    ${paddingXXs(props)}
    ${paddingYXs(props)}
  ${paddingTopXs(props)}
  ${paddingLeftXs(props)}
  ${paddingBottomXs(props)}
  ${paddingRightXs(props)}
  }
  `;

  return style;
};
